/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import documentManagement.DocumentManagement;
import model.Book;
import model.Journal;
import model.Newspaper;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 * HoTen: LeDucTien
 * MSV: 2050531200309
 * LHP: 221LTJNC01
 */
public class EditDocumentFrame extends javax.swing.JFrame {
    Book book;
    Journal journal;
    Newspaper newspaper;
    DocumentManagement documentManagement;
    /**
     * Creates new form SuaTaiLieu
     * @param maTL
     * @throws java.sql.SQLException
     */
    public EditDocumentFrame(String maTL) throws SQLException {
        initComponents();
        book = new Book();
        journal = new Journal();
        newspaper = new Newspaper();
        documentManagement = new DocumentManagement();
        
        // gán giá trị mặc định khi chọn row
        ResultSet rs = documentManagement.getDocumentByID(maTL);
        rs.next();
        String docType = rs.getString("loaiTL");
        docTypeComboBox.setSelectedItem(docType);
        maTLTextField.setText(rs.getString("maTL"));
        tenNXBTextField.setText(rs.getString("tenNXB"));
        soBanPHTextField.setText(rs.getString("soBanPhatHanh"));
        if (docType.equals("Sách")) {
            tenTGTextField.setText(rs.getString("tenTG"));
            soTrangTextField.setText(rs.getString("soTrang"));
        }
        if (docType.equals("Tạp chí")) {
            soPHTextField.setText(rs.getString("soPhatHanh"));
            thangPHTextField.setText(rs.getString("thangPhatHanh"));
        }
        if (docType.equals("Báo")) {
            ngayPHTextField.setText(rs.getString("ngayPhatHanh"));
        }
    }

    EditDocumentFrame() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        thangPHTextField = new javax.swing.JTextField();
        tenNXBTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ngayPHTextField = new javax.swing.JTextField();
        soBanPHTextField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        editDocButton = new javax.swing.JButton();
        tenTGTextField = new javax.swing.JTextField();
        titleLabel = new javax.swing.JLabel();
        docTypeComboBox = new javax.swing.JComboBox<>();
        soTrangTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        maTLTextField = new javax.swing.JTextField();
        soPHTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("LoaiTL");

        jLabel8.setText("ThangPH");

        jLabel3.setText("TenNXB");

        thangPHTextField.setEnabled(false);

        jLabel9.setText("NgayPH");

        jLabel4.setText("SoBanPH");

        ngayPHTextField.setEnabled(false);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("TenTG");

        editDocButton.setText("Edit");
        editDocButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDocButtonActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("EDIT DOCUMENT");

        docTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sách", "Tạp chí", "Báo" }));
        docTypeComboBox.setEnabled(false);
        docTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docTypeComboBoxActionPerformed(evt);
            }
        });

        jLabel6.setText("SoTrang");

        jLabel1.setText("MaTL");

        jLabel7.setText("SoPH");

        maTLTextField.setEnabled(false);

        soPHTextField.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                            .addComponent(editDocButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGap(23, 23, 23)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(soBanPHTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                .addComponent(tenTGTextField)
                                .addComponent(thangPHTextField)
                                .addComponent(soPHTextField)
                                .addComponent(tenNXBTextField)
                                .addComponent(soTrangTextField)
                                .addComponent(ngayPHTextField)
                                .addComponent(maTLTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(docTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(docTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maTLTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tenNXBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(soBanPHTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5))
                    .addComponent(tenTGTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6))
                    .addComponent(soTrangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7))
                    .addComponent(soPHTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8))
                    .addComponent(thangPHTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel9))
                    .addComponent(ngayPHTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(editDocButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void docTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docTypeComboBoxActionPerformed
        String docType  = (String) docTypeComboBox.getSelectedItem();

        // ẩn vùng không cho nhập khi chọn type
        tenTGTextField.setEnabled(false);
        soTrangTextField.setEnabled(false);
        soPHTextField.setEnabled(false);
        thangPHTextField.setEnabled(false);
        ngayPHTextField.setEnabled(false);
        if(docType.equals("Sách")) {
            tenTGTextField.setEnabled(true);
            soTrangTextField.setEnabled(true);
        }
        if(docType.equals("Tạp chí")) {
            soPHTextField.setEnabled(true);
            thangPHTextField.setEnabled(true);
        }
        if(docType.equals("Báo")) {
            ngayPHTextField.setEnabled(true);
        }
    }//GEN-LAST:event_docTypeComboBoxActionPerformed

    private void editDocButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDocButtonActionPerformed
        int confirm = JOptionPane.showConfirmDialog(EditDocumentFrame.this, "Bạn có chắc chắn muốn sửa không");
        if (confirm == JOptionPane.YES_OPTION) {
        
            String docType = (String) docTypeComboBox.getSelectedItem();
             // lỗi chưa nhập dữ liệu
            if (maTLTextField.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Bạn chưa nhập maTL!");
                maTLTextField.requestFocus();
                return;
            }      
            if (tenNXBTextField.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Bạn chưa nhập tenNXB!");
                tenNXBTextField.requestFocus();
                return;
            }
            if (soBanPHTextField.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Bạn chưa nhập soBanPH!");
                soBanPHTextField.requestFocus();
                return;
            }

            if (docType.equals("Sách")) {
                // lỗi chưa nhập dữ liệu
                if (soTrangTextField.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Bạn chưa nhập soTrang!");
                    soTrangTextField.requestFocus();
                    return;
                }
                if (tenTGTextField.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Bạn chưa nhập tenTG!");
                    tenTGTextField.requestFocus();
                    return;
                }

                // set dữ liệu và update
                book.setLoai(docType);
                book.setMaTaiLieu(maTLTextField.getText());
                book.setSoBanPhatHanh(Integer.parseInt(soBanPHTextField.getText()));
                book.setTenNXB(tenNXBTextField.getText());
                book.setTenTG(tenTGTextField.getText());
                book.setSoTrang(Integer.parseInt(soTrangTextField.getText()));
                documentManagement.updateBook(book);
            }
            if (docType.equals("Tạp chí")) {
                // lỗi chưa nhập dữ liệu
                if (soPHTextField.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Bạn chưa nhập soPH!");
                    soPHTextField.requestFocus();
                    return;
                }
                if (thangPHTextField.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Bạn chưa nhập thangPH!");
                    thangPHTextField.requestFocus();
                    return;
                }

                // set dữ liệu và update
                journal.setLoai(docType);
                journal.setMaTaiLieu(maTLTextField.getText());
                journal.setSoBanPhatHanh(Integer.parseInt(soBanPHTextField.getText()));
                journal.setTenNXB(tenNXBTextField.getText());
                journal.setSoPhatHanh(Integer.parseInt(soPHTextField.getText()));
                journal.setThangPhatHanh(thangPHTextField.getText());
                documentManagement.updateJournal(journal);
            }
            if (docType.equals("Báo")){ 
                // lỗi chưa nhập dữ liệu
                if (ngayPHTextField.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Bạn chưa nhập ngayPH!");
                    ngayPHTextField.requestFocus();
                    return;
                }

                // set dữ liệu và update
                newspaper.setLoai(docType);
                newspaper.setMaTaiLieu(maTLTextField.getText());
                newspaper.setSoBanPhatHanh(Integer.parseInt(soBanPHTextField.getText()));
                newspaper.setTenNXB(tenNXBTextField.getText());
                newspaper.setNgayPhatHanh(ngayPHTextField.getText());
                documentManagement.updateNewspaper(newspaper);
            }

            new ListDocumentFrame().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_editDocButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new ListDocumentFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox<String> docTypeComboBox;
    private javax.swing.JButton editDocButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField maTLTextField;
    private javax.swing.JTextField ngayPHTextField;
    private javax.swing.JTextField soBanPHTextField;
    private javax.swing.JTextField soPHTextField;
    private javax.swing.JTextField soTrangTextField;
    private javax.swing.JTextField tenNXBTextField;
    private javax.swing.JTextField tenTGTextField;
    private javax.swing.JTextField thangPHTextField;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
